### ISSUE TITLE
Any plan to have common discord link

### ISSUE THREAD

**Issue by thamaraiselvam** [knutkirkhorn/coinmarketcap-reward-notifier#1]
I was about to build one and you won :p. Thanks for wonderful idea and make it as open source.

If possible can you please share your discord link? Others can join and do not have to manage this container on their own.

**Comment by knutkirkhorn** [comment]
Glad that you liked it! 😄 I will set up a new server as the one I'm currently notifying in is used for other things as well. Will also try setting it up so that other servers can follow that channel.

**Comment by knutkirkhorn** [comment]
@thamaraiselvam you can join the server here: https://discord.gg/CBtDPB5eFE
Added this to the readme as well 😄

**Comment by thamaraiselvam** [comment]
Thanks man 💯
